### ISSUE TITLE
The narrow road to the deep North of version 1.0

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/pyvips#1]
TODO before we can declare 1.0:

- [x] pass the test suite, with as few changes to the suite as possible
- [x] fix run tests via nosetests
- [x] make a base class for our tests
- [x] better temp file handling in test_foreign.py
- [x] some kind of memory mix-up still, we get an occasional crash
- [x] we want this to be a good Python package, but also compatible with the previous Python binding -- if this turns out to be too difficult, we will need to make two packages: this, to provide the actual binding, and another package which sits over this as a compatibility layer
- [x] add GValue tests, see examples
- [x] we need to move almost all of the sample images outside the package
- [x] get it working with py3 -- cffi seems to be quite a bit stricter under python3, this will need some changes
- [x] how do we keep compatibility with old enum code, can we just define `__eq__` on the enum compat classes?
- [x] need a metatype for Image at least so we can support `pyvips.Image.black(1, 1)`
- [x] static docs
- [x] we could support dynamic docs with `help()`, we should test in one of the Python IDEs
- [x] leak test, both malloc and GObject
- [x] benchmark
- [x] remove a lot of the logging: we have too much right now
- [x] add buffer support and link to NumPy and PIL
- [x] test with Windows -- we'll need to at least change the name of the shared library, and maybe look at 32- and 64-bit modes
- [x] travis integration
- [x] test with macOS -- we'll need to at least fix the lib name
- [ ] remove test suite temp files in a way that works on Windows, perhaps make a sub dir for all temp files, and delete that dir on exit
- [x] fix mysterious pypy leaks
- [ ] test GC behaviour under write pressure ... do we need to trigger GC ourselves? or maybe call `__pypy__.add_memory_pressure(n)` for PyPy

Please add more items!

**Comment by jcupitt** [comment]
Benchmark! Here's the old one:

```
john@kiwi:~/GIT/libvips/test (master)$ ./test_all.py 
...................................................................................................................................................................................
----------------------------------------------------------------------
Ran 179 tests in 85.600s

OK
memory: high-water mark 126.94 MB
```

And this new one:

```
john@kiwi:~/GIT/pyvips (master)$ nosetests --logging-level=WARNING
...................................................................................................................................................................................
----------------------------------------------------------------------
Ran 179 tests in 67.818s

OK
memory: high-water mark 126.94 MB
```

So a bit quicker, but it's not dramatic.

**Comment by jcupitt** [comment]
The `py3` branch is supposed to be for python3 compat experiments

**Comment by jcupitt** [comment]
Kleis has fixed all the py3 issues!

**Comment by jcupitt** [comment]
Sample docs:

http://www.rollthepotato.net/~john/html/

**Comment by jcupitt** [comment]
pypy seems to work now too.

**Comment by kleisauke** [comment]
Sample docs with a [Read the Docs theme](https://github.com/rtfd/sphinx_rtd_theme):
https://t0.nl/pyvips/

Let me know if you like it. The branch is located [here](https://github.com/kleisauke/pyvips/tree/sphinx_rtd).

**Comment by jcupitt** [comment]
Hey that looks nice! Sure, let's switch, I'll merge your branch.

It would be great to be able to get sphinx to make a method index. The vimage page (for example) has several 100 methods listed, but no overview, so you have to scroll all the time. I've not been able to find out how to add items to the toc for methods :(

**Comment by jcupitt** [comment]
OK, I've set up gh-pages and revised the README. I'm inclined to call this 1.0 and skip the last two things on the checklist for now. 

What do you think? Shall I pop it on pypi?

**Comment by kleisauke** [comment]
I think it's stable enough for release on PyPI. Let's ship it :shipit:

**Comment by kleisauke** [comment]
I tried to improve the vimage page (by adding a TOC), see: https://t0.nl/pyvips/vimage.html
(the branch is located [here](https://github.com/kleisauke/pyvips/tree/sphinx_toc))

Only the autogenerated methods needs to be added on that page. I've added the `add` method as example (at the bottom). I think it would be nice if everything is alphabetical.

**Comment by jcupitt** [comment]
Oh nice, merged! I'll see if I can list the autogen methods alphabetically.

**Comment by jcupitt** [comment]
I found an extension to generate the toc automatically, it seems to work for the main methods at least.

I'll generate a toc for the auto methods.

**Comment by jcupitt** [comment]
Seems to work!

https://jcupitt.github.io/pyvips/index.html

I've put vimage back all on to one page so you can ^F and search for stuff, hope that's OK.

**Comment by kleisauke** [comment]
Nice! I think it doesn't matter that everything is on one page, the only thing is that it's quite large page now. 

It seems that the `autoautosummary` extension can include attributes. Can we also use that? (for example `bands`, `width`, `height`, etc.)

These methods don't have a summary, by the way:
```
get_offset
get_pspec
get_scale
imageize
```

I think we can exclude `imageize` if we prefix it with an underscore.

**Comment by jcupitt** [comment]
Yes, those need to be tagged as deprecated, get_value and set_value too.

**Comment by jcupitt** [comment]
OK, deprecated and hidden! It's looking better!

You're right, we should mark up attributes like width / height / etc. too. These probably need to be added by hand somewhere, but I think I'm out of time this weekend.

**Comment by jcupitt** [comment]
Ahem, I found some time, it's on pypi!

https://pypi.python.org/pypi/pyvips

I'll close this and open new issues for the remaining items.

I think we've done a great job, Kleis! I intend to have a beer tonight. Cheers!

**Comment by kleisauke** [comment]
Nice! 🍻 

I tried to minimize the size of the vimage page by collapsing all methods by default. When you click on the method or when a anchor is defined in the URL it will expand it's content. See for a live demo here: https://t0.nl/pyvips/vimage.html

What do you think? Branch is located [here](https://github.com/kleisauke/pyvips/tree/sphinx_collapse).

If there is now too many information hidden I could try to make everything that comes after the word `Example:` collapsible (the summary should than stay visible).

**Comment by kleisauke** [comment]
I've made only the method examples collapsible (the summary is still visible) in this version: https://t0.nl/pyvips2/vimage.html

Branch is located [here](https://github.com/kleisauke/pyvips/tree/sphinx_collapse_examples).

It looks neater now, and the height of the vimage page is reduced by 72089 pixels (we now have to scroll less).
