### ISSUE TITLE
Cannot set tile-height via python API

### ISSUE THREAD

**Issue by heri16** [jcupitt/pyvips#23]
`vips-tile-height` is an important parameter for PDF conversion, without it, the performance of this library is very bad.

I have looked at base.py but still could not figure out how to do this in python.

**Comment by jcupitt** [comment]
You're right, there's no API for this parameter in pyvips. 

libvips 8.6 should fix this problem: the chunk height for PDF render has been raised to 5,000 pixels. It's due out in a week or two, or you could try the pre-release here:

https://github.com/jcupitt/libvips/releases/tag/v8.6.0-alpha5

**Comment by heri16** [comment]
This v8.6.0 release likely to appear in homebrew too?

**Comment by jcupitt** [comment]
Yes, everything should update.

**Comment by jcupitt** [comment]
Hopefully this is resolved now, please reopen if you still see bad performance.
