### ISSUE TITLE
write a Image object into std.in buffer

### ISSUE THREAD

**Issue by marcrleonard** [jcupitt/pyvips#25]
I'm working on streaming image sequences into ffmpeg. 
Roughly, this is my code:
```
image_original = pyvips.Image.new_from_file(self.file_path)

p = Popen(['/usr/local/bin/ffmpeg', '-y', '-f', 'image2pipe', '-vcodec', 'mjpeg', '-r', self.fps, '-i', '-', '-r', self.fps, '-f', 'mp4', '-vcodec', 'libx264', '-crf', '26', 'output/{}.mp4'.format(self.animation_name)], stdin=PIPE)

for image in images:
    image.smartcrop(self.output_raster_width, self.output_raster_height)
    image.jpegsave(p.stdin, profile='JPEG')

p.stdin.close()
p.wait()
```
This yields an error, but I suspect I'm not using the right method to do the sdtin write. Is there a good way to handle this use case?

**Comment by jcupitt** [comment]
Hello, unfortunately libvips does not support read and write from pipes. You need to write to a memory buffer, then write that to stdout. 

The fastest way is as a simple C-style memory array. There's an example here of passing an image between vips, numpy and PIL:

https://github.com/jcupitt/pyvips/blob/master/examples/pil-numpy-pyvips.py

Does ffmpeg support piping uncompressed areas of memory like that? If not, I guess you'll want the image coded as a jpg. You can use `write_to_buffer` to make a string containing a jpg-coded image:

https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.write_to_buffer

**Comment by marcrleonard** [comment]
Thanks John, I was able to get it to work using PIL as the mechanism to write to std.in, I just had to read your jpeg buffer as bytes. See below:

```
image_vips = image_offset.smartcrop(self.output_raster_width, self.output_raster_height)
data = image_vips.write_to_buffer('.JPEG', Q=95)
image_bytes = PIL.Image.open(io.BytesIO(data))
image_bytes.save(p.stdin, 'JPEG')
```

I tested the script you provided. Fast indeed! So this begs the question (forgive me if it's a silly question), for anything Vips does at speed is it just using np under the hood? The reason I ask is, I benchmarked both Pillow and Vips doing the same operations of resize, offset, crop, and I actually found Vips to be much slower. The vips code I used is roughly as follows:

```
self.original_image = pyvips.Image.new_from_file(self.file_path)
self.original_image_width = self.original_image.width
self.original_image_height = self.original_image.height

for frame in range(100):
    image_resize = self.original_image.resize(zoom)
    image_offset = image_resize.copy(xoffset = int(x_total), yoffset = int(y_total))
    image_vips = image_offset.smartcrop(self.output_raster_width, self.output_raster_height)
    data = image_vips.write_to_buffer('.JPEG', Q=95)
    image_bytes = PIL.Image.open(io.BytesIO(data))
    image_bytes.save(p.stdin, 'JPEG')
```
Is it slow because it's reading from disk every time (It shouldn't be though, since the object is established at the beginning)? Are the cffi mappings not actually in-play when not utilizing the numpy arrays?

**Comment by jcupitt** [comment]
`smartcrop` is very slow. Try just `crop(left, top, width, height)`.

**Comment by jcupitt** [comment]
libvips has its own pixel functions, it doesn't use numpy. 

You have:

```python
image_vips = image_offset.smartcrop(self.output_raster_width, self.output_raster_height)
data = image_vips.write_to_buffer('.JPEG', Q=95)
image_bytes = PIL.Image.open(io.BytesIO(data))
image_bytes.save(p.stdin, 'JPEG')
```

You're encoding jpg twice there, there's no need. Just do something like:

```python
image_vips = image_offset.smartcrop(self.output_raster_width, self.output_raster_height)
data = image_vips.write_to_buffer('.JPEG', Q=95)
sys.stdout.write(data)
```

**Comment by marcrleonard** [comment]
Hey John, just played off this in the other thread :-)

**Comment by jcupitt** [comment]
Hi again, do you mind if I close this issue? It's confusing having two open for almost the same thing. Let's continue discussion in the other one.
