### ISSUE TITLE
Image.smartcrop seems non-standard

### ISSUE THREAD

**Issue by marcrleonard** [jcupitt/pyvips#26]
When using smart-crop, I did not get results as expected. My assumption was that smartcrop works like a typical crop would - upon specifying the width and height, it uses those dimensions starting from the upper left (0,0) and crops down and right. Here is the code I was using:
```
import pyvips
image_vips = pyvips.Image.new_from_file("IMG_0015_guides.jpg")
cropped = image_vips.smartcrop(1920, 1080)
cropped.jpegsave('output_image.jpeg')
```
Here is the image:
![img_0015_guides_sm](https://user-images.githubusercontent.com/24658895/32418451-5ab50c8e-c227-11e7-8daf-73047938508e.jpg)
Here is the output image
![output_image](https://user-images.githubusercontent.com/24658895/32418455-6d35ebf8-c227-11e7-858e-a1357118b367.jpeg)

Am I misunderstanding how the method works? The resulting image is the correct dimensions, just the wrong placement.

**Comment by jcupitt** [comment]
Hello, try plain `crop`.  Smartcrop searches the image for features like faces or high-saturation areas and tries to centre the crop on that. 

The libvips one is rather like:

https://github.com/jwagner/smartcrop.js

**Comment by jcupitt** [comment]
Crop docs here:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-crop

(`extract_area` is a synonym for `crop`), or smartcrop docs are here:

http://jcupitt.github.io/libvips/API/current/libvips-conversion.html#vips-smartcrop

**Comment by marcrleonard** [comment]
Are there python bindings for vips-crop? I don't see them in the docs, nor did it work when I called it as a method. 
For a better understanding of my workflow, I need resize, offset, crop, write image - in that order. 

```
image_resize = self.original_image.resize(zoom)
image_offset = image_resize.copy(xoffset = int(x_total), yoffset = int(y_total))
image_vips = image_offset.smartcrop(self.output_raster_width, self.output_raster_height)
data = image_vips.write_to_buffer('.JPEG', Q=95)
image_bytes = PIL.Image.open(io.BytesIO(data))
image_bytes.save(p.stdin, 'JPEG')
```
So yes I can chain all these methods together, however, since crop is in the middle, I would have to call the pyvips version of it vs the PIL version. Any suggestions on how to improve this oder of operations?
Many thanks for the help, John.

**Comment by jcupitt** [comment]
Sure, it should work. I see:

```
john@kiwi:~/pics$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> x = pyvips.Image.new_from_file("k2.jpg")
>>> x = x.crop(0, 0, 100, 100)
>>>
```

Historically, the vips operation was called `extract_area`, but that caused great confusion since people expect it to be called `crop`, so `crop` was added as a synonym. Anyway, either should work and they do the same thing.

Your code should be:

```python
im = pyvips.Image.thumbnail('k2.jpg', 128)
im = im.crop(10, 20, 100, 100)
data = im.write_to_buffer('.jpg', Q=95)
sys.stdout.write(data)
```

You seem to be saving to stdin, which puzzles me a little. Are you sure you don't mean stdout?

`thumbnail` is much, much faster than `new_from_file` plus `resize`, since it can do tricks like libjpeg shrink-on-load. It also handles transparency correctly, so you get better quality too. It has a number of useful options, see:

http://jcupitt.github.io/libvips/API/current/libvips-resample.html#vips-thumbnail

**Comment by jcupitt** [comment]
I'll close. Please reopen if there is still a problem.
