### ISSUE TITLE
pyvips can't find the autogenerated-methods

### ISSUE THREAD

**Issue by ElEd2** [jcupitt/pyvips#27]
Hi, 

After doing pip install pyvips, I'm unable to find the [autogenerated methods](https://jcupitt.github.io/pyvips/vimage.html#autogenerated-methods), though I am able to run the example:

```
import pyvips
image = pyvips.Image.new_from_file('my_file.jpg', access='sequential')
image *= [1, 2, 1]
mask = pyvips.Image.new_from_array([[-1, -1, -1],
                                    [-1, 16, -1],
                                    [-1, -1, -1]
                                   ], scale=8)
image = image.conv(mask, precision='integer')
image.write_to_file('x.jpg')
```

Thanks,
Ed

**Comment by ElEd2** [comment]
Hi, 

Actually, my mistake the methods do work, what doesn't work is ipython's autocomplete, which only shows the non-auto-generated functions.

Ed

**Comment by jcupitt** [comment]
Hello, the autogenerated method docs are generated for sphinx by this thing:

https://github.com/jcupitt/pyvips/blob/master/pyvips/voperation.py#L453

pyvips tries to help things like ipython autocomplete by adding help messages for the autogen things. For example:

```
$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyvips
>>> help(pyvips.Image.black)
Help on function call_function in module pyvips.vimage:

call_function(*args, **kwargs)
    Make a black image.
    
    Example:
       out = pyvips.Image.black(width, height, bands = int)
    
    Returns:
        out (Image): Output image
    
    Args:
        width (int): Image width in pixels
        height (int): Image height in pixels
    
    Keyword args:
        bands (int): Number of bands in image
    
    Raises:
        :class:`.Error`
>>>
```

which is made by this thing:

https://github.com/jcupitt/pyvips/blob/master/pyvips/voperation.py#L252

It works for members too, for example:

```
>>> x = pyvips.Image.new_from_file("/data/john/pics/k2.jpg")
>>> help(x.black)
... same as above
```

I don't know much about ipython. What would need to happen to fix the autocomplete?

**Comment by ElEd2** [comment]
Hi, 

Sorry, my knowledge is pretty limited with this kind of thing. 

I see what you mean, indeed the help works. Though dir(pyvips.Image) doesn't show all the functions. 

When I used "from gi.repository import Vips" I could find everything and when I looked at pyvips I couldn't. I assumed the library wasn't finding the .so correctly, so reinstalled in a couple of different ways. Probably worth highlighting this somehow to make sure it doesn't happen to others.

Ed

**Comment by jcupitt** [comment]
There are two Python bindings. libvips comes with one based on pygobject, which has a range of annoying problems. That's the one you get with `from gi.repository import Vips`.

pyvips is a new one based on ffi which is much better. That's the one you install with pip.

Anyway, install with pip and just use `import pyvips` to get the new one.

**Comment by jcupitt** [comment]
`dir()` will only show real methods. pyvips uses `__getattr__` to detect the use of missing methods and look them up in libvips instead, so `dir()` won't work.

**Comment by ElEd2** [comment]
Thanks, it all seems to work well. 
Ed
