### ISSUE TITLE
Missing optional parameters for VIPS_ARGUMENT_OPTIONAL_OUTPUT

### ISSUE THREAD

**Issue by kleisauke** [jcupitt/pyvips#36]
See for example:
https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.labelregions
versus:
http://jcupitt.github.io/libvips/API/current/libvips-morphology.html#vips-labelregions

If a user wants to get the number of regions then they have to call `labelregions` in the following way:
https://github.com/jcupitt/pyvips/blob/d1e690de8ecb947b116a9db606d121bef0a86f90/tests/test_morphology.py#L18

The auto-generated docs haven't described this parameter. To fix this, an libvips argument that has been tagged as `VIPS_ARGUMENT_OPTIONAL_OUTPUT` should also be included in the optional parameters (as boolean type).

**Comment by jcupitt** [comment]
Ooop, you're right, I'll have a look.

**Comment by jcupitt** [comment]
I updated the preformatted docs:

https://jcupitt.github.io/pyvips/vimage.html#pyvips.Image.labelregions

Thanks for pointing out the dumbness Kleis!
