### ISSUE TITLE
magickload svg rgba test fails with ImageMagick 7.0

### ISSUE THREAD

**Issue by felixbuenemann** [jcupitt/pyvips#48]
I have the following error when running `pytest tests/test_foreign.py` on master with vips 8.6.3:

```
============================= test session starts ==============================
platform darwin -- Python 2.7.15, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: /Users/felix/dev/misc/pyvips, inifile: tox.ini
collected 19 items

tests/test_foreign.py ....F..ssss........                                [100%]

=================================== FAILURES ===================================
_________________________ TestForeign.test_magickload __________________________

self = <tests.test_foreign.TestForeign instance at 0x10b4a0ea8>

    @pytest.mark.skipif(not have("magickload") or
                        not os.path.isfile(BMP_FILE),
                        reason="no magick support, skipping test")
    def test_magickload(self):
        def bmp_valid(im):
            a = im(100, 100)

            assert_almost_equal_objects(a, [227, 216, 201])
            assert im.width == 1419
            assert im.height == 1001

        self.file_loader("magickload", BMP_FILE, bmp_valid)
        self.buffer_loader("magickload_buffer", BMP_FILE, bmp_valid)

        # we should have rgba for svg files
        im = pyvips.Image.magickload(SVG_FILE)
>       assert im.bands == 4
E       assert 3 == 4
E        +  where 3 = <pyvips.Image 360x588 ushort, 3 bands, rgb16>.bands

tests/test_foreign.py:333: AssertionError
================ 1 failed, 14 passed, 4 skipped in 6.81 seconds ================
```

libvips is linked against `libMagickCore-7.Q16HDRI.6.dylib` from ImageMagick 7.0.7-29.

I'm not sure if this is the right place to report the issue, since the underlying problem seems to be in libvips.

As far as I can see this issue does not occur with ImageMagick 6.x.

**Comment by jcupitt** [comment]
I'll have a look. Thanks!

**Comment by felixbuenemann** [comment]
I upgrade ImageMagick from 7.0.7-20 to 7.0.7-38 and now the test is passing.

So this was probably an ImageMagick bug.

**Comment by felixbuenemann** [comment]
I also looked at the [ImageMagick ChangeLog](https://raw.githubusercontent.com/ImageMagick/ImageMagick/master/ChangeLog) and it lists the following change for 7.0.7-37:

> 2018-05-29  7.0.7-37  <quetzlzacatenango@image...>
> * Properly initialize SVG color style.

**Comment by felixbuenemann** [comment]
Closing this as it appears to be an ImageMagick issue that has already been fixed in the most recent release.

**Comment by jcupitt** [comment]
Yes, everything seems to work for me with 7.0.7-32.
