### ISSUE TITLE
Image Writing Issue

### ISSUE THREAD

**Issue by shivamchaubey** [jcupitt/pyvips#55]
Hello @jcupitt 
I am having a problem with saving the final result. I am using `merge` function for stitching images. I don't face any problem in saving 25X25 images but when I exceed the limit to 80X80 images it gives an error, image resolution is 480X640px. 
I am using coordinates to merge the images `coor` is a numpy array having coordinate information.
**Attaching sample code.**
```
def stitch(coor):
    global onlyfiles,mypath,row,column
    onlyfiles=np.array(onlyfiles)
    files=onlyfiles.reshape(row,column)
    blend=False
    for r in tqdm(range(files.shape[0])):    
        c=0
        if r==0:
            tile = pyvips.Image.black(coor[r,c][0],coor[r,c][1])
        else:
            tile = pyvips.Image.black(coor[r,c][0],coor[r,c][1]-coor[r-1,c][1])        
        for c in tqdm(range(files.shape[1])): 
            tile1 = pyvips.Image.new_from_file(join(mypath,files[r][c]), access="sequential")
            if r==0:
                x,y=coor[r,c]
            else:
                x,y=coor[r,c][0],coor[r,c][1]-coor[r-1,0][1]
            tile = tile.merge(tile1, 'horizontal', -x, -y, mblend =blend)
        if r>0:
            y=coor[r-1,0][1]
            stitch_img = stitch_img.merge(tile, 'vertical', 0, -y, mblend =blend)    
        else :
            stitch_img=tile
    print (stitch_img.width,stitch_img.height,"width","height")        
    stitch_img.dzsave('test_80X80')
```
**Error:**
```
Traceback (most recent call last):
  File "stitcher_coor.py", line 217, in <module>
  File "stitcher_coor.py", line 101, in stitch
  File "/home/machine/.virtualenvs/project/lib/python3.6/site-packages/pyvips/vimage.py", line 783, in call_function
  File "/home/machine/.virtualenvs/project/lib/python3.6/site-packages/pyvips/voperation.py", line 188, in call
pyvips.error.Error: unable to call dzsave
  vips__file_open_read: unable to open file "/home/machine/Desktop/iter6/set4_80X80/25_13.jpeg" for reading
unix error: Too many open files
```
I have also set open files limit to the maximum.

**Comment by jcupitt** [comment]
Hello, you need to raise the maximum number of open files. I have mine set at 64000, for example.

```
john@yingna ~ $ ulimit -n
64000
```

Exactly how to raise the number will need a bit of searching. It seems to vary a lot between linuxes.

**Comment by shivamchaubey** [comment]
Thanks @jcupitt 

I tried to set it before but the maximum `ulimit - n` was  4096 and I failed to set it more. I followed this issue [https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu](https://superuser.com/questions/1200539/cannot-increase-open-file-limit-past-4096-ubuntu ) and it worked well. 
Can you suggest any other pipeline which I should implement to decrease RAM uses? Right now its taking 13.5GB for 80X80 images.  I am first making each rows and then merging all the rows vertically.

**Comment by jcupitt** [comment]
You could build as sets of 2x2 blocks. So join the four in the top left as

```
A B 
C D
```

Then the next 2x2 block, and so on. Then do another pass and join up the 2x2 blocks in the same way, and repeat until the whole image is joined.

You can drop the concurrency down. Try `VIPS_CONCURRENCY=1` before running your program.

**Comment by shivamchaubey** [comment]
Thanks for the suggestion. Closing this issue.
