### ISSUE TITLE
Can't invert PNG images with transparency properly

### ISSUE THREAD

**Issue by Diniboy1123** [jcupitt/pyvips#57]
I am using the latest version of libvips and pyvips, and I tried to load this [image](https://user-images.githubusercontent.com/29148882/43419292-d2ae9d68-9440-11e8-80f5-dcdaaae59e2e.png)...

I did:

```py
image = pyvips.Image.new_from_file('test.png')
image = image.invert()
image.pngsave('invert.png', strip=True)
```

And I got the following result:

![inverted](https://user-images.githubusercontent.com/29148882/43419398-0b9271b8-9441-11e8-91d1-2d27973e0d06.png)

What can cause this? The lib doesn't support alpha channels?

**Comment by jcupitt** [comment]
Hello, it's inverted all the bands. If you want to just invert RGB and leave alpha alone, you'll need to break off the alpha and reattach it. 

```python
#!/usr/bin/python

import sys
import pyvips

x = pyvips.Image.new_from_file(sys.argv[1])

alpha = x[-1]
x = x[0:x.bands - 1]
    
x = x.invert()

x = x.bandjoin(alpha)
    
x.write_to_file(sys.argv[2])
```

Now:

```
$ ./invert-rgba.py head.png x.png
```

Makes:

![x](https://user-images.githubusercontent.com/580843/43426223-ed34a40a-944c-11e8-93ee-c84183c9319e.png)

You could also use `linear()` to apply a different linear transform to each channel like this:

```python
x = pyvips.Image.new_from_file(sys.argv[1])

x = x * [-1, -1, -1, 1] + [255, 255, 255, 0]

x.write_to_file(sys.argv[2])
```

This probably seems a bit odd. libvips started as a scientific image processing library, so it really just sees images as huge arrays of numbers. Things like alpha channel support are much later additions and are generally not automatic.

**Comment by Diniboy1123** [comment]
Thanks, it worked! 😃
